namespace Sony.Vita.SavedGame
{
	public enum ErrorCode
	{
		SG_OK,
		SG_ERR_COMMON_DIALOG_BUSY,
		SG_ERR_BUSY,
		SG_ERR_FAILED,
		SG_ERR_BAD_STATE,
		SG_ERR_INDEX_OUT_OF_RANGE,
		SG_ERR_ICON_PATH_TOO_LONG,
		SG_ERR_TOO_MANY_SLOTS,
		SG_ERR_DIALOG_OPEN,
		SG_ERR_BAD_FILE,
		SG_ERR_NO_SPACE_QUOTA,
		SG_ERR_NO_SPACE,
		SG_ERR_NO_MEM_CARD,
		SG_ERR_NO_DATA,
		SG_ERR_SLOT_NOT_FOUND
	}
}
